In [1]:
import numpy as np

### Numpy Fancy Indexing

In [2]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
[x[3],x[5],x[8]]

[3, 5, 8]

In [4]:
ind = [3,5,8]
x[ind]

array([3, 5, 8])

### numpy.array 的比较

In [5]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [7]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [8]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [9]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [10]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
np.sum(x <= 3)

4

In [12]:
np.count_nonzero(x <= 3)

4

#### 是否有非0元素

In [13]:
np.any(x == 0)

True

#### 所有元素都满足条件返回True

In [14]:
np.all(x >= 0)

True

In [15]:
np.sum((x > 3) & (x < 10))

6