## numpy.array 基础

In [1]:
import numpy as np

In [2]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 查看数据类型
nparr.dtype

dtype('int64')

In [4]:
nparr2 = np.array([1,2,3.0])
nparr2.dtype

dtype('float64')

### 其他创建 numpy.array 的方法

In [10]:
# 创建含有10个0的np.array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(10).dtype

dtype('float64')

In [13]:
# 创建指定数值的矩阵
np.full(shape=(3,5),fill_value=12.0)

array([[12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.],
       [12., 12., 12., 12., 12.]])

### arange

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# 步长还可以传入浮点数
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

In [17]:
# 从起始点到终止点的区间里等长的截出个数（0到20的区间里等长截出10个数）
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

### random

In [18]:
# 生成随机数
np.random.randint(0,10)  # 两个参数，结果是一个数

9

In [20]:
np.random.randint(0,10,size=10) # 三个参数，结果是生成向量的个数，

array([5, 5, 9, 2, 9, 8, 2, 5, 9, 6])

In [21]:
# 随机生成二维矩阵
np.random.randint(4,8,size=(3,5))

array([[4, 4, 4, 6, 6],
       [6, 4, 7, 7, 6],
       [5, 7, 6, 5, 7]])

In [22]:
# 随机种子，保持随机生成的数据是一样
np.random.seed(666)

In [23]:
# 生成一个0到1之间的随机向量
np.random.random(10)

array([0.70043712, 0.84418664, 0.67651434, 0.72785806, 0.95145796,
       0.0127032 , 0.4135877 , 0.04881279, 0.09992856, 0.50806631])

In [24]:
# 生成一个0到1之间的随机矩阵
np.random.random((3,5))

array([[0.20024754, 0.74415417, 0.192892  , 0.70084475, 0.29322811],
       [0.77447945, 0.00510884, 0.11285765, 0.11095367, 0.24766823],
       [0.0232363 , 0.72732115, 0.34003494, 0.19750316, 0.90917959]])

In [27]:
# 随机生成 均值为0，方差为1 符合正态分布的随机矩阵
np.random.normal(0,1,size=(3,5))

array([[ 0.53928565, -1.54984701,  0.72946452, -0.32695477,  1.14133677],
       [ 0.45243662, -2.23496877,  1.27047766, -0.72928821,  1.35925255],
       [-1.20990266, -0.04618272, -0.44118244,  0.46953431,  0.44325817]])

## numpy.array 基础操作

In [31]:
x = np.arange(10)
x
# reshape 将一维数组转化二维数组
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [32]:
# 查看是几维数组
x.ndim

1

In [33]:
X.ndim

2

In [34]:
# 返回一个数组，可以查看几维
x.shape
X.shape

(3, 5)

### 数据访问

In [35]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x[0]

0

In [37]:
x[-1]

9

In [38]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
X[2,2] # 访问的是第二行第二列的数

12

In [41]:
# 切片
X[:2,:3]  # 前两行  前三列

array([[0, 1, 2],
       [5, 6, 7]])

In [42]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [44]:
# 取第一行
X[0,:]

array([0, 1, 2, 3, 4])

In [45]:
# 取第一列
X[:,0]

array([ 0,  5, 10])

In [46]:
# 修改子矩阵数据会改变原矩阵的数据，所以修改数据前要copy
subX = X[:2,:3].copy()
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [47]:
subX[0,0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [48]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### reshape

In [49]:
x.shape

(10,)

In [50]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
# 将一维数组转化二维矩阵
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
A = x.reshape(1,10)
A

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
x.reshape(10,-1) # -1让系统自动分配

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## 合并操作

In [55]:
x = np.array([1,2,3])
y = np.array([3,2,1])

### concatenate

In [56]:
np.concatenate([x,y]) # 合并成一维

array([1, 2, 3, 3, 2, 1])

In [57]:
B = np.array([[1,2,3],
             [4,5,6]])

In [58]:
np.concatenate([B,B]) # 默认是沿着行方向合并

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([B,B],axis=1) # 沿着列方向合并

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [60]:
z = np.array([666,666,666])
z

array([666, 666, 666])

In [61]:
np.concatenate([B,z.reshape(1,-1)])  # 将一维数组和二维矩阵合并，先将一维数组 reshape 成二维矩阵相同的维度再进行合并

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [62]:
np.vstack([B,z]) # 系统自动沿着行方向进行合并

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [63]:
C = np.full((2,2),100)
C

array([[100, 100],
       [100, 100]])

In [65]:
np.hstack([B,C]) # 系统自动沿着列方向进行合并

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 分割操作

In [66]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
x1,x2,x3 = np.split(x,[3,7]) # 一维数组的分割
x1

array([0, 1, 2])

In [69]:
x2

array([3, 4, 5, 6])

In [70]:
x3

array([7, 8, 9])

In [71]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [73]:
A1,A2 = np.split(A,[2]) # 默认是按 行方向分割
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [74]:
B1,B2 = np.split(A,[2],axis=1) # 按列方向分割
B1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [75]:
A1,A2 = np.vsplit(A,[2]) # 垂直方向分割
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [76]:
B1,B2 = np.hsplit(A,[2]) # 水平方向分割
B1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

## 运算

In [77]:
%%time
L = np.array(np.arange(1000000))
A = L * 2
A

CPU times: user 6.26 ms, sys: 6.64 ms, total: 12.9 ms
Wall time: 11.5 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

#### 二维矩阵运算

In [78]:
X = np.arange(1,16).reshape(3,5)
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [79]:
X * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [80]:
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [81]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [82]:
np.sin(X) 

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [83]:
np.power(3,X) # X 的 3次方

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [84]:
np.log(X) # 以 1 为底的 log 函数

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [85]:
np.log10(X) # 以 10 为底的 log 函数

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

### 矩阵之间的运算

In [86]:
A = np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [87]:
B = np.full((2,2),10)
B

array([[10, 10],
       [10, 10]])

In [88]:
A + B

array([[10, 11],
       [12, 13]])

In [89]:
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [90]:
A * B # 对应元素相乘

array([[ 0, 10],
       [20, 30]])

In [91]:
A.dot(B) # 矩阵乘法

array([[10, 10],
       [50, 50]])

In [92]:
A.T  # 矩阵的转置，行转列，列转行

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [93]:
v = np.array([1,2])
v

array([1, 2])

In [94]:
A

array([[0, 1],
       [2, 3]])

In [95]:
v * A

array([[0, 2],
       [2, 6]])

In [96]:
v.dot(A)

array([4, 7])

In [98]:
A.dot(v)

array([2, 8])

## 矩阵的逆

In [99]:
A

array([[0, 1],
       [2, 3]])

In [102]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [104]:
A.dot(invA) # 矩阵的逆 和原矩阵相乘 对角线为1

array([[1., 0.],
       [0., 1.]])

In [105]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

### 伪逆矩阵

In [106]:
X = np.arange(16).reshape(2,8)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [107]:
pinvX = np.linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -3.46944695e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

## 聚合操作

In [108]:
L = np.random.random(100)
L

array([0.90238039, 0.85178834, 0.41808196, 0.39347627, 0.01622051,
       0.29921337, 0.35377822, 0.89350267, 0.78613657, 0.77138693,
       0.42005486, 0.77602514, 0.46430814, 0.18177017, 0.8840256 ,
       0.71879227, 0.6718813 , 0.25656363, 0.43080182, 0.01645358,
       0.23499383, 0.51117131, 0.29200924, 0.50189351, 0.49827313,
       0.10377152, 0.44644312, 0.96918917, 0.73847112, 0.71955061,
       0.89304339, 0.96267468, 0.19705023, 0.71458996, 0.16192394,
       0.86625477, 0.62382025, 0.95945512, 0.52414204, 0.03643288,
       0.72687158, 0.00390984, 0.050294  , 0.99199232, 0.2122575 ,
       0.94737066, 0.45154055, 0.99879467, 0.64750149, 0.70224071,
       0.42958177, 0.16777476, 0.11813309, 0.93788262, 0.91099744,
       0.39799354, 0.92530327, 0.74549922, 0.78982636, 0.63770852,
       0.99274137, 0.47610554, 0.10211419, 0.87256332, 0.75612704,
       0.29919884, 0.18625652, 0.49435351, 0.0408955 , 0.47835228,
       0.3089902 , 0.92058026, 0.91794568, 0.46848893, 0.23431

In [109]:
np.sum(L) # 求和

52.51144206728903

In [110]:
np.min(L) # 最小值

0.0011210912356498515

In [111]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [112]:
np.sum(X)

120

In [113]:
np.sum(X,axis=0) # 沿着垂直方向，每一列的和

array([24, 28, 32, 36])

In [114]:
np.sum(X,axis=1) # 沿着水平方向，每一行的和

array([ 6, 22, 38, 54])

In [115]:
np.mean(X) # 平均值

7.5

In [116]:
np.median(X) # 中位数

7.5

In [117]:
np.var(X) # 方差

21.25

In [118]:
np.std(X) # 标准差

4.6097722286464435

## 排序和索引

In [121]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [123]:
np.random.shuffle(x) # 乱序
x

array([ 5, 13,  4,  3,  9,  8,  6, 12,  2, 10,  1,  7,  0, 14, 11, 15])

In [124]:
np.sort(x) # 排序

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])